import { config } from "dotenv";

config();

const {
  DISCORD_TOKEN,
  RAMP_CLIENT_ID,
  RAMP_CLIENT_SECRET,
  GUILD_ID,
  DISCORD_ID,
  GOOGLE_SERVICE_ACCOUNT_EMAIL,
  GOOGLE_PRIVATE_KEY,
  GMAIL_ADDRESS,
  GMAIL_APP_PASSWORD,
  GOOGLE_SHEETS_ID,
} = process.env;

if (
  !DISCORD_TOKEN ||
  !RAMP_CLIENT_ID ||
  !RAMP_CLIENT_SECRET ||
  !GUILD_ID ||
  !DISCORD_ID ||
  !GOOGLE_SERVICE_ACCOUNT_EMAIL ||
  !GOOGLE_PRIVATE_KEY ||
  !GMAIL_ADDRESS ||
  !GMAIL_APP_PASSWORD ||
  !GOOGLE_SHEETS_ID
) {
  throw new Error("Missing environment variables");
}

export const AppConfig = {
  DISCORD_TOKEN,
  DISCORD_ID,
  RAMP_CLIENT_ID,
  RAMP_CLIENT_SECRET,
  GUILD_ID,
  GOOGLE_SERVICE_ACCOUNT_EMAIL,
  GOOGLE_PRIVATE_KEY,
  GMAIL_ADDRESS,
  GMAIL_APP_PASSWORD,
  GOOGLE_SHEETS_ID,
};
